### ISSUE TITLE
请问怎么解决webpack4版本时的冲突问题的？

### ISSUE THREAD

**Issue by Yunnkii** [itPoet/vue-webpack-todoapp#2]

**Comment by Yunnkii** [comment]
vue4@1.0.0 build C:\Users\Acer\Desktop\vue4
> webpack --config webpack.config.js

**Comment by LuoRiWuSheng** [comment]
> vue4@1.0.0 build C:\Users\Acer\Desktop\vue4
> 
> > webpack --config webpack.config.js

我的是webpack4 没啥问题啊，你把错误贴上开看看
