### ISSUE TITLE
如何部署到gitpage

### ISSUE THREAD

**Issue by Mr-Vincent** [itPoet/vue-webpack-todoapp#6]
大兄弟我发现你的demo应用是部署在git page上的，我知道静态博客可以通过hexo去部署，不知道你这个demo是如何部署上去的。请教一下

**Comment by XPoet** [comment]
我用的是GitHub Pages，新建仓库，上传将打包后的代码，在仓库设置里开启Pages服务，具体参考：https://github.com/itPoet/vue-webpack-dist-todoapp

**Comment by Mr-Vincent** [comment]
全静态的站点可以这样整，如果有api请求的话这样就不能这样玩了对吧。
