### ISSUE TITLE
npm install报错，烦请看下，谢谢。

### ISSUE THREAD

**Issue by stonesingsong** [itPoet/vue-webpack-todoapp#8]
npm install报错，烦请看下，谢谢。
![image](https://user-images.githubusercontent.com/14824330/49262531-d8cbe600-f481-11e8-99b0-a99b67c3cca4.png)

**Comment by LuoRiWuSheng** [comment]
> npm install报错，烦请看下，谢谢。
> ![image](https://user-images.githubusercontent.com/14824330/49262531-d8cbe600-f481-11e8-99b0-a99b67c3cca4.png)

这个应该不是包安装错了  是你安装到一半，有退出，导致有的包安装进去了，有的没有安装进去
删除 node_modules目录。整个删除，重新 npm install

**Comment by LuoRiWuSheng** [comment]
> npm install报错，烦请看下，谢谢。
> ![image](https://user-images.githubusercontent.com/14824330/49262531-d8cbe600-f481-11e8-99b0-a99b67c3cca4.png)

这种不是没有权限，请删除node_modules，然后重新 npm install
